"""Reproduce compact Unicode grapheme properties from pinned upstream data."""
import argparse
import hashlib
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[1]
VERSION = '17.0.0'
BASE = f'https://www.unicode.org/Public/{VERSION}/ucd/'
INPUTS = {
    'GraphemeBreakProperty.txt': BASE + 'auxiliary/GraphemeBreakProperty.txt',
    'emoji-data.txt': BASE + 'emoji/emoji-data.txt',
    'DerivedCoreProperties.txt': BASE + 'DerivedCoreProperties.txt',
    'GraphemeBreakTest.txt': BASE + 'auxiliary/GraphemeBreakTest.txt',
    'LICENSE.txt': 'https://www.unicode.org/license.txt',
}
CLASSES = ['Other', 'CR', 'LF', 'Control', 'Extend', 'ZWJ', 'Regional_Indicator',
           'Prepend', 'SpacingMark', 'L', 'V', 'T', 'LV', 'LVT']


def rows(path):
    for line in path.read_text(encoding='utf8').splitlines():
        fields = [part.strip() for part in line.split('#')[0].split(';')]
        if len(fields) < 2:
            continue
        bounds = fields[0].split('..')
        yield int(bounds[0], 16), int(bounds[-1], 16), fields[1:]


def generate(cache, output):
    values = [0] * 0x110000
    for lo, hi, fields in rows(cache / 'GraphemeBreakProperty.txt'):
        if fields[0] not in ('LV', 'LVT'):  # Algorithmic Hangul syllables avoid 798 redundant ranges.
            values[lo:hi + 1] = [CLASSES.index(fields[0])] * (hi - lo + 1)
    for lo, hi, fields in rows(cache / 'emoji-data.txt'):
        if fields[0] in ('Extended_Pictographic', 'Emoji_Presentation', 'Emoji'):
            for code in range(lo, hi + 1):
                values[code] |= {'Extended_Pictographic': 0x40, 'Emoji_Presentation': 0x80, 'Emoji': 0x100}[fields[0]]
    for lo, hi, fields in rows(cache / 'DerivedCoreProperties.txt'):
        if fields[0] == 'InCB':
            incb = ['None', 'Consonant', 'Extend', 'Linker'].index(fields[1])
            for code in range(lo, hi + 1):
                values[code] |= incb << 4
    ranges = []
    start = 0
    for code in range(1, len(values) + 1):
        if code == len(values) or values[code] != values[start]:
            if values[start]:
                ranges.append((start, code - 1, values[start]))
            start = code
    output.mkdir(parents=True, exist_ok=True)
    # Constant arrays, two ranges per line; deterministic and readable by the Cangjie formatter.
    for part, offset in enumerate(range(0, len(ranges), 200)):
        data = ranges[offset:offset + 200]
        source = ['// Generated by .dev/unicode/generate.py; Unicode 17.0.0 / Unicode-3.0.',
                  '// See .dev/unicode/LICENSE.txt and sources.json. Do not hand-edit.',
                  'package sdl.text', '',
                  f'internal let GRAPHEME_DATA_{part}: Array<(UInt32, UInt32, UInt32)> = [']
        for i in range(0, len(data), 2):
            source.append('    ' + ', '.join(f'(0x{a:X}, 0x{b:X}, 0x{p:X})' for a, b, p in data[i:i + 2]) + ',')
        source[-1] = source[-1].rstrip(',')
        source.extend([']', ''])
        (output / f'grapheme_data_{part}.cj').write_text('\n'.join(source), encoding='utf8')
    print(f'Unicode {VERSION}: {len(ranges)} property ranges, {(len(ranges) + 199) // 200} arrays')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache', type=Path, default=REPO / 'target/dev/text-quality/unicode')
    parser.add_argument('--output', type=Path, default=REPO / 'src/text')
    parser.add_argument('--record', action='store_true', help='record hashes only for an intentional Unicode update')
    args = parser.parse_args()
    args.cache.mkdir(parents=True, exist_ok=True)
    manifest = {} if args.record else json.loads((ROOT / 'sources.json').read_text(encoding='utf8'))['files']
    actual = {}
    for name, url in INPUTS.items():
        path = args.cache / name
        if not path.exists():
            with urllib.request.urlopen(url, timeout=60) as response:
                path.write_bytes(response.read())
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if not args.record and manifest[name]['sha256'] != digest:
            raise ValueError(f'Unicode source hash mismatch: {name}')
        actual[name] = {'url': url, 'sha256': digest}
    if args.record:
        (ROOT / 'sources.json').write_text(json.dumps({'version': VERSION, 'files': actual}, indent=2) + '\n', encoding='utf8')
    (ROOT / 'LICENSE.txt').write_bytes((args.cache / 'LICENSE.txt').read_bytes())
    (ROOT / 'GraphemeBreakTest.txt').write_bytes((args.cache / 'GraphemeBreakTest.txt').read_bytes())
    generate(args.cache, args.output)


if __name__ == '__main__':
    main()
