#!/usr/bin/env python3
"""Stable command-line entry point for CangjieSDL development checks."""

import argparse
import os
import sys
import unittest
from collections.abc import Callable, Sequence
from pathlib import Path


DEV_ROOT = Path(__file__).resolve().parent
REPOSITORY_ROOT = DEV_ROOT.parent
if str(DEV_ROOT) not in sys.path:
    sys.path.insert(0, str(DEV_ROOT))

# Keep generated bytecode with other build output instead of under `.dev`.
configured_cache = os.environ.get("PYTHONPYCACHEPREFIX")
cache_root = Path(configured_cache) if configured_cache else REPOSITORY_ROOT / "target" / "dev" / "pycache"
if not cache_root.is_absolute():
    cache_root = REPOSITORY_ROOT / cache_root
cache_root = cache_root.resolve()
os.environ["PYTHONPYCACHEPREFIX"] = str(cache_root)
sys.pycache_prefix = str(cache_root)

from sdl_dev.checks import doc_snippets, docs
from sdl_dev.e2e import examples


Command = Callable[[Sequence[str] | None], int | None]


def _without_arguments(command: Callable[[], int | None]) -> Command:
    def invoke(arguments: Sequence[str] | None = None) -> int | None:
        if arguments:
            raise SystemExit(f"this command accepts no arguments: {' '.join(arguments)}")
        return command()
    return invoke


def _tool_tests(arguments: Sequence[str] | None = None) -> int:
    if arguments:
        raise SystemExit("test tools accepts no additional arguments")
    suite = unittest.TestLoader().discover(str(DEV_ROOT / "tests"), top_level_dir=str(DEV_ROOT))
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


COMMANDS: dict[tuple[str, ...], Command] = {
    ("check", "docs"): _without_arguments(docs.main),
    ("check", "snippets"): doc_snippets.main,
    ("test", "examples"): examples.main,
    ("test", "tools"): _tool_tests,
}


def _usage() -> str:
    commands = "\n".join(f"  {' '.join(parts)}" for parts in sorted(COMMANDS))
    return f"usage: python .dev/cli.py <command> [arguments]\n\ncommands:\n{commands}"


def main(argv: Sequence[str] | None = None) -> int:
    arguments = list(sys.argv[1:] if argv is None else argv)
    if not arguments or arguments[0] in {"-h", "--help"}:
        print(_usage())
        return 0

    for parts, command in sorted(COMMANDS.items(), key=lambda item: -len(item[0])):
        if tuple(arguments[:len(parts)]) == parts:
            try:
                result = command(arguments[len(parts):])
                return 0 if result is None else int(result)
            except (OSError, RuntimeError, ValueError) as error:
                print(f"{' '.join(parts)} failed: {error}", file=sys.stderr)
                return 2

    parser = argparse.ArgumentParser(usage=_usage(), add_help=False)
    parser.error(f"unknown command: {' '.join(arguments[:2])}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
